services:
  web:
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
    container_name: hosting_web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      # Admin app (zatím placeholder) – bude servírovaná na /
      - ./app:/var/www/html:rw
      # Zákaznické weby – subdoménový (customer.localhost:8080) i adresářový (localhost:8080/~customer) hosting
      - ./data/www:/srv/www:rw
      # apache config – pro nastavení virtual hostů, přesměrování atd.
      - ./docker/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf:ro
      # FTP - přístup k users db, pro manipulaci přes pure-pw
      - ./data/ftp/passwd:/etc/pure-ftpd/passwd:rw
      # Dynamicka zmena zaznamu na hostitelskem stroji (vyzaduje chmod 666 /etc/hosts na hostiteli)
      - /etc/hosts:/host_etc_hosts:rw
    depends_on:
      - db
    networks:
      - hosting_net

  db:
    image: mariadb:10.11
    container_name: hosting_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data/mariadb:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    networks:
      - hosting_net

  ftp:
    image: stilliard/pure-ftpd
    container_name: hosting_ftp
    command: /bin/sh -c "/run.sh -l puredb:/etc/pure-ftpd/passwd/pureftpd.pdb -E -j -R -P $$PUBLICHOST"
    restart: unless-stopped
    environment:
      PUBLICHOST: "localhost"
      # Pasivní porty (domluvený rozsah)
      ADDED_FLAGS: "--passiveportrange 30000:30009"
    volumes:
      - ./data/www:/home:rw
      - ./data/ftp/passwd:/etc/pure-ftpd/passwd:rw
    ports:
      - "2121:21"
      - "30000-30009:30000-30009"
    networks:
      - hosting_net

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: hosting_pma
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:80"
    networks:
      - hosting_net

networks:
  hosting_net:
    driver: bridge
