site_name: BSPWE Hosting Documentation
theme:
  name: material

nav:
  - Home: index.md
  - Aplikace: APP.md
  - Bezpečnost: SECURITY.md
  - Databáze: DB.md
  - FTP: FTP.md
  - Web: WEB.md
  - Jak na MkDocs: mkdocs_tutorial.md
  - Návod pro klienty: USER_GUIDE.md

markdown_extensions:
  - admonition